/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.firstapplication;

/**
 *
 * @author ee16xkg
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jLoginButton = new javax.swing.JButton();
        jPassLabel = new javax.swing.JLabel();
        jPasswordTextField = new javax.swing.JPasswordField();
        jCalculatorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInput1TextField = new javax.swing.JTextField();
        jInput2TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jOutputTextField = new javax.swing.JTextField();
        jSumButton = new javax.swing.JButton();
        jDifferenceButton = new javax.swing.JButton();
        jFactorButton = new javax.swing.JButton();
        jQuotientButton = new javax.swing.JButton();
        jExponentButton = new javax.swing.JButton();
        jClearButton1 = new javax.swing.JButton();
        jVolumePanel = new javax.swing.JPanel();
        jDimension1Label = new javax.swing.JLabel();
        jDimension2Label = new javax.swing.JLabel();
        jDimension3Label = new javax.swing.JLabel();
        jAnswerLabel = new javax.swing.JLabel();
        jInput4TextField = new javax.swing.JTextField();
        jInput5TextField = new javax.swing.JTextField();
        jInput6TextField = new javax.swing.JTextField();
        jAnswerTextField = new javax.swing.JTextField();
        jRectangleButton = new javax.swing.JButton();
        jCylinderButton = new javax.swing.JButton();
        jConeButton = new javax.swing.JButton();
        jPyramidButton = new javax.swing.JButton();
        jSphereButton = new javax.swing.JButton();
        jClearButton2 = new javax.swing.JButton();
        jStatusPanel = new javax.swing.JPanel();
        jStatusMessageLabel = new javax.swing.JLabel();
        jStatusAnimationLabel = new javax.swing.JLabel();
        jProgressCompletionBar = new javax.swing.JProgressBar();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNameLabel.setText("User Name:");

        jNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTextFieldActionPerformed(evt);
            }
        });

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jPassLabel.setText("Password:");

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLoginButton)
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNameLabel)
                    .addComponent(jPassLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jPasswordTextField))
                .addGap(63, 63, 63))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassLabel)
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLoginButton)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jLabel1.setText("Input 1");

        jLabel2.setText("Input 2");

        jInput1TextField.setText("0.0");

        jInput2TextField.setText("0.0");

        jLabel3.setText("Output");

        jOutputTextField.setText("0.0");

        jSumButton.setText("+");
        jSumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumButtonActionPerformed(evt);
            }
        });

        jDifferenceButton.setText("-");
        jDifferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDifferenceButtonActionPerformed(evt);
            }
        });

        jFactorButton.setText("*");
        jFactorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFactorButtonActionPerformed(evt);
            }
        });

        jQuotientButton.setText("/");
        jQuotientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuotientButtonActionPerformed(evt);
            }
        });

        jExponentButton.setText("^");
        jExponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExponentButtonActionPerformed(evt);
            }
        });

        jClearButton1.setText("Clear");
        jClearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCalculatorPanelLayout = new javax.swing.GroupLayout(jCalculatorPanel);
        jCalculatorPanel.setLayout(jCalculatorPanelLayout);
        jCalculatorPanelLayout.setHorizontalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jInput1TextField))
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jInput2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                        .addGap(43, 43, 43)
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jClearButton1)))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jSumButton)
                        .addGap(18, 18, 18)
                        .addComponent(jDifferenceButton)
                        .addGap(18, 18, 18)
                        .addComponent(jFactorButton)
                        .addGap(18, 18, 18)
                        .addComponent(jQuotientButton)
                        .addGap(18, 18, 18)
                        .addComponent(jExponentButton)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jCalculatorPanelLayout.setVerticalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jInput1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jInput2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClearButton1))
                .addGap(38, 38, 38)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSumButton)
                    .addComponent(jDifferenceButton)
                    .addComponent(jFactorButton)
                    .addComponent(jQuotientButton)
                    .addComponent(jExponentButton))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Calculator", jCalculatorPanel);

        jDimension1Label.setText("Length/Radius:");

        jDimension2Label.setText("Width/Base:");

        jDimension3Label.setText("Height:");

        jAnswerLabel.setText("Answer:");

        jInput4TextField.setText("0.0");

        jInput5TextField.setText("0.0");

        jInput6TextField.setText("0.0");

        jAnswerTextField.setText("0.0");

        jRectangleButton.setText("Rectangle");
        jRectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRectangleButtonActionPerformed(evt);
            }
        });

        jCylinderButton.setText("Cylinder");
        jCylinderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCylinderButtonActionPerformed(evt);
            }
        });

        jConeButton.setText("Cone");
        jConeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConeButtonActionPerformed(evt);
            }
        });

        jPyramidButton.setText("Pyramid");
        jPyramidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPyramidButtonActionPerformed(evt);
            }
        });

        jSphereButton.setText("Sphere");
        jSphereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSphereButtonActionPerformed(evt);
            }
        });

        jClearButton2.setText("Clear");
        jClearButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jVolumePanelLayout = new javax.swing.GroupLayout(jVolumePanel);
        jVolumePanel.setLayout(jVolumePanelLayout);
        jVolumePanelLayout.setHorizontalGroup(
            jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jVolumePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDimension1Label)
                    .addComponent(jDimension2Label)
                    .addComponent(jDimension3Label)
                    .addComponent(jAnswerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInput4TextField)
                    .addComponent(jInput5TextField)
                    .addComponent(jInput6TextField)
                    .addComponent(jAnswerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jClearButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jVolumePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jRectangleButton)
                .addGap(18, 18, 18)
                .addComponent(jCylinderButton)
                .addGap(18, 18, 18)
                .addComponent(jConeButton)
                .addGap(18, 18, 18)
                .addComponent(jSphereButton)
                .addGap(18, 18, 18)
                .addComponent(jPyramidButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jVolumePanelLayout.setVerticalGroup(
            jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jVolumePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDimension1Label)
                    .addComponent(jInput4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jVolumePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInput5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDimension2Label))
                        .addGap(21, 21, 21)
                        .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDimension3Label)
                            .addComponent(jInput6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jVolumePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jClearButton2)))
                .addGap(18, 18, 18)
                .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnswerLabel))
                .addGap(42, 42, 42)
                .addGroup(jVolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRectangleButton)
                    .addComponent(jCylinderButton)
                    .addComponent(jConeButton)
                    .addComponent(jPyramidButton)
                    .addComponent(jSphereButton))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Volume", jVolumePanel);

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainTabbedPane)
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jStatusPanel.setBackground(new java.awt.Color(204, 204, 255));
        jStatusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jStatusPanel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jStatusMessageLabel.setText("My First Application is running");

        javax.swing.GroupLayout jStatusPanelLayout = new javax.swing.GroupLayout(jStatusPanel);
        jStatusPanel.setLayout(jStatusPanelLayout);
        jStatusPanelLayout.setHorizontalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStatusMessageLabel)
                .addGap(18, 18, 18)
                .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jStatusAnimationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jStatusPanelLayout.setVerticalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusMessageLabel)
                    .addComponent(jStatusAnimationLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBarMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBarMain.setForeground(new java.awt.Color(0, 51, 204));

        jMenu1.setText("File");
        jMenuBarMain.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBarMain.add(jMenu2);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:        
        String name = jNameTextField.getText();
        String pass = jPasswordTextField.getText();
        
        if(pass.equals("1234") && name.equals("Xavier")){
        jStatusMessageLabel.setText(jNameTextField.getText()+" is logged in...");
        jMainTabbedPane.setSelectedIndex(1);
        }
        else{
        jStatusMessageLabel.setText("Username or Password not recognised");
        }
        
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jSumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.valueOf(jInput1TextField.getText());
        double input2 = Double.valueOf(jInput2TextField.getText());
        
        double output = input1 + input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jSumButtonActionPerformed

    private void jDifferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDifferenceButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.valueOf(jInput1TextField.getText());
        double input2 = Double.valueOf(jInput2TextField.getText());
        
        double output = input1 - input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jDifferenceButtonActionPerformed

    private void jFactorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFactorButtonActionPerformed
        // TODO add your handling code here:
        
        double input1 = Double.valueOf(jInput1TextField.getText());
        double input2 = Double.valueOf(jInput2TextField.getText());
        
        double output = input1 * input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jFactorButtonActionPerformed

    private void jQuotientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuotientButtonActionPerformed
        // TODO add your handling code here:
        
        double input1 = Double.valueOf(jInput1TextField.getText());
        double input2 = Double.valueOf(jInput2TextField.getText());
        if (input2 != 0){
        
        double output = input1 / input2;
        jOutputTextField.setText(String.valueOf(output));
        }
        else{
        jOutputTextField.setText("Cannot divide by zero!");
        }
    }//GEN-LAST:event_jQuotientButtonActionPerformed

    private void jExponentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExponentButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.valueOf(jInput1TextField.getText());
        int input2 = Integer.valueOf(jInput2TextField.getText());
        double output = Power(input1,input2);
        jOutputTextField.setText(String.valueOf(output));
            
    }//GEN-LAST:event_jExponentButtonActionPerformed

    private void jNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameTextFieldActionPerformed

    private void jRectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRectangleButtonActionPerformed
        // TODO add your handling code here:
        double length = Double.valueOf(jInput4TextField.getText());
        double width = Double.valueOf(jInput5TextField.getText());
        double height = Double.valueOf(jInput6TextField.getText());
        
        double answer = RectangularVolume(length, width, height);
        
        jAnswerTextField.setText(String.valueOf(answer));
            
    }//GEN-LAST:event_jRectangleButtonActionPerformed

    private void jCylinderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCylinderButtonActionPerformed
        // TODO add your handling code here:
        
        double radius = Double.valueOf(jInput4TextField.getText());
        double height = Double.valueOf(jInput6TextField.getText());
        
        double answer = CylinderVolume(radius, height);
        
        jAnswerTextField.setText(String.valueOf(answer));
    }//GEN-LAST:event_jCylinderButtonActionPerformed

    private void jConeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConeButtonActionPerformed
        // TODO add your handling code here:
        double radius = Double.valueOf(jInput4TextField.getText());
        double height = Double.valueOf(jInput6TextField.getText());
        
        double answer = ConeVolume(radius, height);
        
        jAnswerTextField.setText(String.valueOf(answer));
    }//GEN-LAST:event_jConeButtonActionPerformed

    private void jPyramidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPyramidButtonActionPerformed
        // TODO add your handling code here:
        
        double base = Double.valueOf(jInput5TextField.getText());
        double height = Double.valueOf(jInput6TextField.getText());
            
        double answer = SquareBasedPyramidVolume(base, height);
        
        jAnswerTextField.setText(String.valueOf(answer));
    }//GEN-LAST:event_jPyramidButtonActionPerformed

    private void jSphereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSphereButtonActionPerformed
        // TODO add your handling code here:
        double radius = Double.valueOf(jInput4TextField.getText());

        double answer = SphereVolume(radius);

        jAnswerTextField.setText(String.valueOf(answer));
    }//GEN-LAST:event_jSphereButtonActionPerformed

    private void jClearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButton2ActionPerformed
        // TODO add your handling code here:
        jInput4TextField.setText("");
        jInput5TextField.setText("");
        jInput6TextField.setText("");
        jAnswerTextField.setText("");
    }//GEN-LAST:event_jClearButton2ActionPerformed

    private void jClearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButton1ActionPerformed
        // TODO add your handling code here:
        jInput1TextField.setText("");
        jInput2TextField.setText("");
        jOutputTextField.setText("");
    }//GEN-LAST:event_jClearButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    public static double Power(double base, int exp) {
        /* When Base is Zero */
        if (exp == 0)
        return 1;
        
        /* For Negative Powers */
        else if(exp < 0)
        return (1 / Power(base, -exp));
        
        /* For Positive Real Numbers */
        else
        return base * Power(base, exp-1);   
}
    
    public static double RectangularVolume(double length, double width, double height) {
        
        return length * width * height;
        
    }
    
    public static double CylinderVolume(double radius, double height) {
        
        return (Power(radius, 2) * 3.14 * height);
        
    }
    
    public static double ConeVolume(double radius, double height) {
        
        return (Power(radius, 2) * 3.14 * height / 3);
        
    }
    
    public static double SphereVolume(double radius) {
        
        return (Power(radius, 3) * 3.14 * 4 / 3);
        
    }
    
    public static double SquareBasedPyramidVolume(double base, double height) {
        
        return (Power(base, 2) * height / 3);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAnswerLabel;
    private javax.swing.JTextField jAnswerTextField;
    private javax.swing.JPanel jCalculatorPanel;
    private javax.swing.JButton jClearButton1;
    private javax.swing.JButton jClearButton2;
    private javax.swing.JButton jConeButton;
    private javax.swing.JButton jCylinderButton;
    private javax.swing.JButton jDifferenceButton;
    private javax.swing.JLabel jDimension1Label;
    private javax.swing.JLabel jDimension2Label;
    private javax.swing.JLabel jDimension3Label;
    private javax.swing.JButton jExponentButton;
    private javax.swing.JButton jFactorButton;
    private javax.swing.JTextField jInput1TextField;
    private javax.swing.JTextField jInput2TextField;
    private javax.swing.JTextField jInput4TextField;
    private javax.swing.JTextField jInput5TextField;
    private javax.swing.JTextField jInput6TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JTextField jOutputTextField;
    private javax.swing.JLabel jPassLabel;
    private javax.swing.JPasswordField jPasswordTextField;
    private javax.swing.JProgressBar jProgressCompletionBar;
    private javax.swing.JButton jPyramidButton;
    private javax.swing.JButton jQuotientButton;
    private javax.swing.JButton jRectangleButton;
    private javax.swing.JButton jSphereButton;
    private javax.swing.JLabel jStatusAnimationLabel;
    private javax.swing.JLabel jStatusMessageLabel;
    private javax.swing.JPanel jStatusPanel;
    private javax.swing.JButton jSumButton;
    private javax.swing.JPanel jVolumePanel;
    // End of variables declaration//GEN-END:variables
}
